name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2 Server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/aws_key
          chmod 600 ~/.ssh/aws_key

      - name: Add EC2 to known hosts
        run: |
          ssh-keyscan -H ec2-54-206-115-2.ap-southeast-2.compute.amazonaws.com >> ~/.ssh/known_hosts

      - name: Deploy code to EC2 via SCP
        run: |
          scp -o StrictHostKeyChecking=no -i ~/.ssh/aws_key -r ./ ubuntu@ec2-54-206-115-2.ap-southeast-2.compute.amazonaws.com:/var/www/html/errawrs/project-errawrs

      - name: Restart Nginx (if needed)
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/aws_key ubuntu@ec2-54-206-115-2.ap-southeast-2.compute.amazonaws.com 'sudo systemctl restart nginx'
