name: CI/CD Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Copy files to EC2
        run: |
          scp -o StrictHostKeyChecking=no -i ~/.ssh/aws_key -r ./ ubuntu@your-ec2-public-dns:/var/www/html/errawrs

      - name: SSH into EC2 and pull latest changes
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/aws_key ubuntu@your-ec2-public-dns << 'EOF'
            cd /var/www/html/errawrs
            git pull origin main
            sudo systemctl restart nginx
          EOF
